### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by drjah** [vinbigdata-medical/vindr-spinexr#1]
I am working on a study of vertebral morphology and wanted to explore using this code to understand how osteophytes effect morphology metrics. 
I go the code running - up to a point.
After the first block of iterations, it runs inference on the test set, and the inference runs on all 2077 images, but then crashes with the error messages below. Is there a fix for this? To get the code to work, detectron was cloned from facebookresearch and installed from the local clone.

Thanks

Traceback (most recent call last):
  File "/SSD1/detectron2/detectron2/engine/train_loop.py", line 150, in train
    self.after_step()
  File "/SSD1/detectron2/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/SSD1/detectron2/detectron2/engine/hooks.py", line 555, in after_step
    self._do_eval()
  File "/SSD1/detectron2/detectron2/engine/hooks.py", line 528, in _do_eval
    results = self._func()
  File "/SSD1/detectron2/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/SSD1/detectron2/detectron2/engine/defaults.py", line 617, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/SSD1/detectron2/detectron2/evaluation/evaluator.py", line 204, in inference_on_dataset
    results = evaluator.evaluate()
  File "/SSD1/detectron2/detectron2/evaluation/coco_evaluation.py", line 206, in evaluate
    self._eval_predictions(predictions, img_ids=img_ids)
TypeError: _eval_predictions() missing 1 required positional argument: 'predictions'

**Comment by yuzeWAN** [comment]
Sorry, I have encountered the same problem. Have you solved this problem?

**Comment by AmbiakaTT** [comment]
I encountered the same too, has anyone figured out the solution?

**Comment by benhuhaudau** [comment]
This is because _eval_predictions in coco_evaluation.py has the same function name as coco_evaluator.py
Change the name of _eval_predictions in coco_evaluation and you will be fine.

Another thing, in sparsernn.yaml. You need to change the last 3 lines:
TEST:
  EVAL_PERIOD: 500
VIS_PERIOD: 500
To 50000 Iterations or else it would finish at 500
